modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/Blackout03/Chaos-Additions/issues"
license="All Rights Reserved."

[[mods]]
modId="chaosadditions"
version="${file.jarVersion}"
displayName="Chaos Additions"
updateJSONURL="https://raw.githubusercontent.com/Blackout03/Chaos-Additions/1.16.5-Forge/update.json"
displayURL="https://blackout03.github.io/mods/chaos-additions.html"
authors="Blackout"
description='''Some new Additions to Chaos Awakens!'''
itemIcon="chaosadditions:ultimate_aiot"

[[dependencies.chaosadditions]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"

[[dependencies.chaosadditions]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17]"
ordering="NONE"
side="BOTH"

[[dependencies.chaosadditions]]
modId="chaosawakens"
mandatory=true
versionRange="[0.11,)"
ordering="AFTER"
side="BOTH"

[[dependencies.chaosadditions]]
modId="geckolib3"
mandatory=true
versionRange="[3.0.92,)"
ordering="AFTER"
side="BOTH"
