modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/Blackout03/Chaos-Additions/issues"
displayURL="https://blackout03.github.io/mods/chaos-additions.html"
license="All Rights Reserved."

[[mods]]
modId="chaosadditions"
version="${file.jarVersion}"
displayName="Chaos Additions"
authors="Blackout"
description='''Some new Additions to Chaos Awakens!'''
itemIcon="chaosadditions:ultimate_aiot"

[[dependencies.chaosadditions]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"

[[dependencies.chaosadditions]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17]"
ordering="NONE"
side="BOTH"

[[dependencies.chaosadditions]]
modId="chaosawakens"
mandatory=true
versionRange="[0.9.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.chaosadditions]]
modId="geckolib3"
mandatory=true
versionRange="[3.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.chaosadditions]]
modId="projecte"
mandatory=false
versionRange="[PE1.0,]"
ordering="AFTER"
side="BOTH"
