modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/Blackout03/Chaos-Awakens-Additions/issues"
displayURL=""
license="All Rights Reserved."

[[mods]]
modId="caadditions"
version="${file.jarVersion}"
displayName="Chaos Awakens Additions"
description='''Some Additions to Chaos Awakens!'''
itemIcon="caadditions:ultimate_aiot"
configBackground="chaosawakens:textures/gui/advancement_bg.png"

[[dependencies.caadditions]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"

[[dependencies.caadditions]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17]"
ordering="NONE"
side="BOTH"

[[dependencies.caadditions]]
modId="chaosawakens"
mandatory=true
versionRange="[0.8,)"
ordering="NONE"
side="BOTH"

[[dependencies.caadditions]]
modId="geckolib3"
mandatory=true
versionRange="[3.0,)"
ordering="NONE"
side="BOTH"
